name: "build-test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        npm install
    - name: lint
      run: |
        npm run lint
    - name: build
      run: |
        npm run build
    - name: test
      run: |
        npm run test
  test_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with: 
        xml_path: ${{ github.workspace }}/__tests__/resource/ktlint-report.xml